### ISSUE TITLE
client.connect

### ISSUE THREAD

**Issue by alisa74** [KeganHollern/DotaMatch#1]
hi Kegan,
I tried using your code in order to make lobbies but when it comes to client.Connect(); the code freezes in this function and does not proceed to the next line .
could you please explain more about this ?

**Comment by KeganHollern** [comment]
Connect is a synchronous function. If it fails to connect it can halt the program. I get around it by doing something like this:

`            Thread Temp = new Thread(() => {
                client.Connect();
                ready = true;
            });
            Temp.Start();`

Using the "ready" variable to determine if the client is ready to start hosting matches.

I plan to add an async version of this function and deprecate the existing one soon.

**Comment by KeganHollern** [comment]
Closing this. If the issue persists I'll look into it. I verified client connection still works yesterday.
